/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author 722741_lehnsen
 */
public class FrmT1cotizacion extends javax.swing.JFrame {
     public double precio=0;
     public String compra="";
     public String muestra="";
     public double interes=0;
    /**
     * Creates new form FrmT1cotizacion
     */
    public FrmT1cotizacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbx_articulos_.removeAllItems();
        cbx_articulos_.addItem("SELECCION");
        cbx_articulos_.addItem("Televisor");
        cbx_articulos_.addItem("Heladera");
        cbx_articulos_.addItem("Cocina");
        cbx_articulos_.addItem("Computadora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbx_articulos_ = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_precio_ = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbn_6meses_ = new javax.swing.JRadioButton();
        rbn_12meses_ = new javax.swing.JRadioButton();
        rbn_24meses_ = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_interes_ = new javax.swing.JLabel();
        btn_total_ = new javax.swing.JButton();
        btn_cuota_ = new javax.swing.JButton();
        btn_limpiar_ = new javax.swing.JButton();
        btn_salir_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plazo:");

        jLabel1.setText("Articulos");

        cbx_articulos_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_articulos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_articulos_ActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio en USD$");

        txt_precio_.setBackground(new java.awt.Color(204, 255, 255));
        txt_precio_.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plazo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setName("Plazo:"); // NOI18N

        buttonGroup1.add(rbn_6meses_);
        rbn_6meses_.setText("6 meses");
        rbn_6meses_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn_6meses_ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbn_12meses_);
        rbn_12meses_.setText("12 meses");

        buttonGroup1.add(rbn_24meses_);
        rbn_24meses_.setText("24 meses");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbn_6meses_)
                    .addComponent(rbn_12meses_)
                    .addComponent(rbn_24meses_))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbn_6meses_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbn_12meses_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbn_24meses_)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel4.setText("Interes");

        txt_interes_.setBackground(new java.awt.Color(204, 255, 255));
        txt_interes_.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_total_.setText("Total");
        btn_total_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_total_ActionPerformed(evt);
            }
        });

        btn_cuota_.setText("Cuota");
        btn_cuota_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuota_ActionPerformed(evt);
            }
        });

        btn_limpiar_.setText("Limpiar");
        btn_limpiar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_ActionPerformed(evt);
            }
        });

        btn_salir_.setText("Salir");
        btn_salir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_total_)
                                .addGap(49, 49, 49)
                                .addComponent(btn_limpiar_))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_precio_, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(txt_interes_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btn_salir_))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btn_cuota_)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(cbx_articulos_, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_articulos_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_precio_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_interes_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(btn_cuota_)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_total_)
                    .addComponent(btn_limpiar_)
                    .addComponent(btn_salir_))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_articulos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_articulos_ActionPerformed
        int posicion=0; 
        posicion=cbx_articulos_.getSelectedIndex();
        switch (posicion) {
            case 1:
                precio=1800;
                muestra = "3%";
                compra="Televisor";
                break;
            case 2:
                precio=1750;
                muestra = "5%";
                compra="Heladera";
                break;
            case 3:
                precio=2000;
                muestra = "8%";
                compra="Cocina";
                break;
            case 4:
                precio=2600;
                muestra = "10%";
                compra="Computadora";
                break;
        }
        txt_precio_.setText(String.valueOf(precio));
        txt_interes_.setText(String.valueOf(muestra));
    }//GEN-LAST:event_cbx_articulos_ActionPerformed

    private void btn_limpiar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_ActionPerformed
        txt_precio_.setText(null);
        txt_interes_.setText(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btn_limpiar_ActionPerformed

    private void btn_cuota_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuota_ActionPerformed
            if (rbn_6meses_.isSelected()==true){
                interes=precio/6;
            }
            if (rbn_12meses_.isSelected()==true){
                interes=precio/12;
            }
            if (rbn_24meses_.isSelected()==true){
                interes=precio/24;
            }
            JOptionPane.showMessageDialog(null, "Gracias por usar el programa");

    }//GEN-LAST:event_btn_cuota_ActionPerformed

    private void rbn_6meses_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn_6meses_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn_6meses_ActionPerformed

    private void btn_salir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_ActionPerformed
        int resp=0;
        resp= JOptionPane.showConfirmDialog
        (null,"Esta seguro de cerrar el programa",
                "Salida",JOptionPane.YES_NO_OPTION);
        if (resp==0) {
            JOptionPane.showMessageDialog(null, "Gracias por usar el programa");
            System.exit(0);
        }
    }//GEN-LAST:event_btn_salir_ActionPerformed

    private void btn_total_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_total_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_total_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmT1cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmT1cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmT1cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmT1cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmT1cotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cuota_;
    private javax.swing.JButton btn_limpiar_;
    private javax.swing.JButton btn_salir_;
    private javax.swing.JButton btn_total_;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbx_articulos_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbn_12meses_;
    private javax.swing.JRadioButton rbn_24meses_;
    private javax.swing.JRadioButton rbn_6meses_;
    private javax.swing.JLabel txt_interes_;
    private javax.swing.JLabel txt_precio_;
    // End of variables declaration//GEN-END:variables
}
